
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: otp
  datasource:
    url: jdbc:postgresql://localhost:5433/otp
    username: postgres
    password: postgres
    hikari:
      schema: otp
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${spring.datasource.hikari.schema}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: 81.30.105.54:29092
    producer:
      acks: all
    consumer:
      group-id: send-otp-group

otp:
  kafka:
    send-otp:
      enabled: true
      topic-in: Send.Otp.IN.V1
      topic-out: Send.Otp.OUT.V1
